on: 
  workflow_dispatch:
    inputs:
      domain:
        description: 'domain to knock'
        required: true
        default: 'github.com'
        
jobs:
  knock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test for subdomains
        run: "knock ${{ github.event.inputs.domain ))"

